#Defaults to 8981 in test, 8982 in development and 8983 in production.

development:
  solr:
    hostname: 127.0.0.1
    port: 8982
    path: /solr
    log_level: INFO

test:
  solr:
    hostname: 127.0.0.1
    port: 8981
    path: /solr
    log_level: WARNING
            
production:
  solr:
    hostname: 127.0.0.1
    port: 8983
    path: /solr
    log_level: WARNING

adam:
  solr:
    port: 8982
    hostname: 127.0.0.1
    path: /solr
    log_level: INFO
